server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
info:
  version: @project.version@
  stage: dev

kafka:
  bootstrap.servers: localhost:9092
  concurrency: 5
  streams:
    replication-factor: 1
  ssl:
    enable: false
    keystore-location: "src/main/resources/cert/kenny-k.struzhkin.p12"
    keystore-password: "kenny"
    key-password: "kenny"
    server-password: "kenny12"
    server-keystore-location: "src/main/resources/cert/truststore.p12"
  task:
    deduplication:
      input:
        topic: invoice-test
      output:
        topic: invoice-test-deduplicated